### ISSUE TITLE
main menu.unity and sandbox.unity cant be opened!

### ISSUE THREAD

**Issue by DerpyTheHedgeone** [SnesFX/Utopia-Decomp#2]
help i dont know why but i cant open the main menu.unity or sandbox.unity it says that it is encrypted or built in a newer version, i am trying to open these because i dont know how to make a playable sonic in a new scene

**Comment by TyDevX** [comment]
Try re-downloading/cloning with this: https://bitbucket.org/ty_1991/utopia-decomp/src/main/

**Comment by DerpyTheHedgeone** [comment]
now it says that it couldnt download main menu.unity and sandbox.unity

**Comment by TyDevX** [comment]
Try pressing the 3 dots on the side and using the download button

**Comment by TyDevX** [comment]
also use this link instead: https://bitbucket.org/tydevstoragelmao/utopia-decomp/src/main/

**Comment by DerpyTheHedgeone** [comment]
if i download it, it says that it is corrupted or encrypted or built in a new version
if i clone it, it says it couldnt download main menu.unity and sandbox.unity

**Comment by DerpyTheHedgeone** [comment]
i dont know if its because im switching target to windows instead of android

**Comment by TyDevX** [comment]
Nah, when I tried it said some crap about gitlfs storage being fully used so yeah

**Comment by DerpyTheHedgeone** [comment]
is there no solution?

**Comment by TyDevX** [comment]
I mean I could easily just decompile the game again and send the Unity project to you on discord, but it'd be on Unity 2018 instead of 2019 since that's the ver I have installed rn

**Comment by DerpyTheHedgeone** [comment]
what about google drive or mediafire or megadrive?

**Comment by TyDevX** [comment]
https://www.mediafire.com/file/8b5phxhdbs21y37/Utopia+Decomp+Backup.zip/file

**Comment by DerpyTheHedgeone** [comment]
it finaly worked! weird how there is invisible objects but thanks

**Comment by SnesFX** [comment]
Idk why stuff went invisible but like it could be because of upgrading it to a diff unity ver, also that's my other acc lol
